//
//  FCModel.swift
//  FoodCollector
//
//  Created by Guy Freedman on 10 Nov 2014.
//  Copyright (c) 2014 UPP Project . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import CoreLocation
import Foundation


/// App Data Model as a Singletone.


class FCModel : NSObject {
    
    var locationManager = CLLocationManager()
    var appDataStoreManager = FCAppDataStoreManager()
    var readyToLaunchUI:Bool = false
    var foodCollectorWebServer:FCFoodCollectorWebServer!
    var publications = [FCPublication]()
    var pushNotificationHandler = FCUserNotificationHandler()
    var userCreatedPublications = [FCPublication]()
    
    ///
    ///loads publications from disk and fetches data from server
    // 
    
    func prepareForUI () {
        
    }
    
    ///
    ///posts NSNotification when the downloaded data is ready
    ///
    
    func postFetchedDataReadyNotification () {
        
    }
    
    /// removes a Publication to Publications array
    ///
    
    func removePublication(arg1:AnyObject) {
        
    }
    
    ///
    /// add a Publication to Publications array
    ///
    
    func addPublication(arg1:AnyObject) {
        
    }
    
    ///
    /// called after init when all data was successfully fetched from the server
    
    
    func postApplicationDataDidChangeNotification() {
        
    }
}

extension FCModel {

        //SingleTone Shared Instance
        class var sharedInstance : FCModel {
            
            struct Static {
                static var onceToken : dispatch_once_t = 0
                static var instance : FCModel? = nil
            }
            
            dispatch_once(&Static.onceToken) {
                Static.instance = FCModel()
            }
            
            return Static.instance!
        }
}


